Repository adopted-ember-addons/ember-electron, pull requests merged in 2021-01, with the labels that each got.

#676 Set `contextIsolation` to false for tests
  lib/test-support/index.js
Labels: enhancement

#697 Run Windows and MacOS tests with GH Actions
  .appveyor.yml
  .github/workflows/main.yml
  package.json
Labels: internal

#700 Change `vendor.js` to `app.js` in documentation
  tests/dummy/app/templates/docs/faq/routing-and-asset-loading.md
Labels: documentation

#702 Parallelize end-to-end tests
  .github/workflows/main.yml
Labels: internal

#701 Make embroider-compatible
  index.js
  package.json
  tests/dummy/app/templates/docs/faq/routing-and-asset-loading.md
Labels: enhancement

#705 Update CSP instructions
  tests/dummy/app/templates/docs/guides/csp.md
Labels: documentation
