Repository adopted-ember-addons/ember-electron, pull requests merged in 2021-03, with the labels that each got.

#747 pass allowFileAccess option to electron-devtools-installer
  forge/files/src/index.js
  forge/files/tests/index.js
Labels: enhancement

#751 Use process.execPath is the test runner
  lib/test-runner.js
Labels: bug

#769 Include info on context isolation in documentation
  tests/dummy/app/templates/docs/guides/development-and-debugging.md
Labels: documentation
