Repository adopted-ember-addons/ember-electron, pull requests merged in 2021-05, with the labels that each got.

#811 feat: expose forge publish api
  lib/commands/base.js
  lib/commands/make.js
  lib/tasks/publish.js
  node-tests/integration/commands/make-test.js
Labels: enhancement

#815 Document the new publish functionality
  tests/dummy/app/templates/docs/guides/usage.md
Labels: documentation

#833 Add dependabot automerge
  .github/workflows/main.yml
Labels: internal

#838 Use node 12 for testing
  .github/workflows/main.yml
  package.json
Labels: internal
